<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtVerifiedLoginSuccess</name>
   <tag></tag>
   <elementGuidId>bb528a1e-db0c-445e-aa03-e8d037991935</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;post-11752&quot;]/div/div[1]/div/div/div/div[1]/div/div[4]/div[1]/div/div[4]/h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
